version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.21.6

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: golangci-lint run -v --timeout=600s
      - run: go test -v ./...
      - run: go build .
