name: Conventional Commits

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check Conventional Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ''
